version: '3.8'

services:
  boot-app:
    image: everestp/chat-app-backend01
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_URI = mongodb+srv://everest12:Kaiseho@12@cluster0.o6rw2.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - app-network

networks:
  app-network:  # ✅ Make sure this is present at the bottom
