version: '3.8'

services:
  boot-app:
    image: everestp/chat-app-backend000
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_URI = mongodb+srv://everest:1234@cluster0.yvsvt.mongodb.net/
    networks:
      - app-network

networks:
  app-network:  # ✅ Make sure this is present at the bottom
